name: 'Pull main to windmill workspace'
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  # schedule:
  #  - cron:  '0 * * * *'

env:
  WMILL_URL: https://dev-windmill.thit.io
  WMILL_WORKSPACE: tonghualabs

jobs:
  sync:
    environment: windmill
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      # (push will pull first to detect conflicts and only push actual changes)
      - name: Pull changes
        run: |
         deno run --unstable -A  https://deno.land/x/wmill@v1.175.0/main.ts workspace switch __automation
         deno run --unstable -A  https://deno.land/x/wmill@v1.175.0/main.ts sync pull --yes --fail-conflicts
         
          

      # autocommit the new .wmill state after the push                                                             
      # - uses: stefanzweifel/git-auto-commit-action@v4
